### ISSUE TITLE
There are no versions of the packages you are using

### ISSUE THREAD

**Issue by rosgori** [JWarmenhoven/DBDA-python#6]
It is preferable to show on `README.md` the versions of `numpy` or `pymc3` or  `matplotlib` that you have used in order to create the notebooks.

You can include the version of every package in a file called `requirements.txt, for example:

https://github.com/jvns/pandas-cookbook

or something like this at the end:

https://github.com/aloctavodia/BAP/blob/master/code/Chp7/07_Mixture_Models.ipynb

**Comment by JWarmenhoven** [comment]
You are right, I should include that kind of information.
I think I will go for this IPython extension: https://github.com/rasbt/watermark
