### ISSUE TITLE
Wrong array dimensions in Chapter 24?

### ISSUE THREAD

**Issue by mad-lab** [JWarmenhoven/DBDA-python#7]
Getting the following error when trying to run code for Chapter 24:

`trace1['a1a2'][:,j1,j2])`
`ValueError: could not broadcast input array from shape (20000) into shape (5000)`

Which happens in this part of the code:

```
# Transforming the trace data to sum-to-zero values
m = np.zeros((Nx1Lvl,Nx2Lvl, n_samples*4))
b1b2 = m.copy()

for (j1,j2) in np.ndindex(Nx1Lvl,Nx2Lvl):
        m[j1,j2,:] =  (trace1['a0'] +
                     trace1['a1'][:,j1] +
                     trace1['a2'][:,j2] +
                     trace1['a1a2'][:,j1,j2])
```

I think the issue boils down to the size of the variable _m_, which is set to have dimensions (_Nx1Lvl_, _Nx2Lvl_, 5000). However, the _trace1_ object, ends up producing arrays of length = 20,000 because it concatenates the results of all 4 MCMC chains together:

```
In [78]: len(trace1['a0'])
Out[78]: 20000
```

If I change the dimensions of m to be 

`m = np.zeros((Nx1Lvl,Nx2Lvl, n_samples*4))`

the code seems to run just fine.

I'm new to PyMC3 so perhaps this is due to how the trace objects works on different versions of PyMC3. I'm using PyMC3 version 3.4.1

**Comment by JWarmenhoven** [comment]
You are absolutely right in your conclusion; the sampling has changed somewhat through the different versions. I just ran the notebook in version 3.5 (using CPU) and it started two chains of `n_samples` each, which created a trace of 10000 samples in total. In earlier versions, the sampler would start a single chain by default.

Perhaps I should change the code like this:
```python
# Transforming the trace data to sum-to-zero values
m = np.zeros((Nx1Lvl,Nx2Lvl, trace1.nchains*n_samples))
b1b2 = m.copy()

for (j1,j2) in np.ndindex(Nx1Lvl,Nx2Lvl):
        m[j1,j2] =  (trace1['a0'] +
                     trace1['a1'][:,j1] +
                     trace1['a2'][:,j2] +
                     trace1['a1a2'][:,j1,j2])
```
Thanks for the feedback!
