### ISSUE TITLE
Chapter 10: Wrong number of coin flips for Model 2?

### ISSUE THREAD

**Issue by OlafHaag** [JWarmenhoven/DBDA-python#9]
Hey, I was just quickly skimming over the Chapter 10 code and after it says

    Model 2 - Two theta variables without pseudo priors

    Coin is flipped nine times, resulting in six heads.

`y2 = pm.Bernoulli('y2', theta, observed=[1,1,1,1,1,0,0,0])`
I can only count **8 flips** resulting in **5 heads**. It also says so on the plate of the graphical model.

**Comment by JWarmenhoven** [comment]
Hi,

Good catch, thanks! 
I will update it.

Edit: seems like I need to review the entire repository and do updates for Arviz plotting...
